### ISSUE TITLE
Allow to return Input Object types

### ISSUE THREAD

**Issue by vwkd** [graphql/graphql-spec#1029]
It seems Input Object types are a strict subset of Object types. It should be possible to return Input Object types.

One use case is to generate a CRUD API from a user-supplied schema, where Object types use none of the features like inheritance, field arguments, or non-null circular dependencies that differentiate them from Input Object types. Currently, the user has to duplicate every type, once as Input Object type for mutations, and once as Output Object type for queries. If Input Objects were allowed to be returned, the user could only define Input Object types and reuse them as both input types in mutations and return types in queries.

This seems to be a common concern judging by questions on stackoverflow and issues on GitHub. Some excerpts

> If fields are the same, e.g. query type can be "type User {name: String}", same as UserInput. Why not type and input type are interchangeable?

[stackoverflow.com](https://stackoverflow.com/questions/45911490/why-does-graphql-choose-to-use-an-input-type?noredirect=1&lq=1#comment78897727_45914008)

> I understand the difference between output type fields (which can have parameters and can thus be thought of like methods) and input structures (which may have different nullability conditions than their related output type) but it seems to me that the conceptual nature of an input type is a subset of the conceptual nature of an output type, and it is frustrating not to be able to use it as such.

https://github.com/graphql/graphql-js/issues/599#issuecomment-1293351924

**Comment by benjie** [comment]
Ref: https://github.com/graphql/graphql-spec/issues/932#issuecomment-1055158221
