### ISSUE TITLE
Casting Error in GraphQL C# Library

### ISSUE THREAD

**Issue by lavanyadeepak** [graphql/graphql-spec#1064]
We are facing a piquant situation using GraphQLClient's SendQueryAsync method to call Monday.com API. The line goes like this

var response = await graphQLClient.SendQueryAsync<dynamic>(request)

If the server returns a proper JSON it is all fine. However if the server returns a message like Complexity budget exhausted, query cost 30001 budget remaining 29984 out of 1000000 reset in 8 seconds, it throws a message like Error converting value Complexity budget exhausted, query cost 30001 budget remaining 29984 out of 1000000 reset in 8 seconds to type GraphQL.GraphQLError. Path errors[0] line 1 position 305

How do we configure this graphqlclient to cast the string into GraphQL Error or are we missing something else?

**Comment by benjie** [comment]
Hi @lavanyadeepak, I'm afraid we can't help you with that; you need to raise your issue against the software that you are using (the GraphQL C# Library?).

**Comment by lavanyadeepak** [comment]
Thank you @benjie . As suggested by you I have posted the same to the C# Library here: https://github.com/graphql-dotnet/graphql-dotnet/issues/3791
