### ISSUE TITLE
Dynamic Input Object Types

### ISSUE THREAD

**Issue by bringking** [graphql/graphql-spec#140]
Is is possible in the spec to have "dynamic" object input types? The use case being something like these Sequelize `where` clauses -

``` js
{
  rank: {
    $or: {
      $lt: 1000,
      $eq: null
    }
  }
}
```

These clauses can be nested to join the logic. e.g the object can have $or, and that object can have `n` nested $or + `n` nested $and statements. 

``` js
{
  rank: {
    $or: {
      $lt: 1000
    },
     $or: {
      $gt: 1500
    },
    $and: {
      $ne: 1500
    }
   ...
  }
}
```

Could these be modeled as an input type?

**Comment by sorenbs** [comment]
Fwiw, at Graphcool we generate a filter input type pretty much like you describe based on the fields in a given model.

This allows arbitrary queries like this in a typed system (and  auto-complete in GraphiQL):

```
allArtists(filter:{OR:[{name:"Madonna"}, {AND:[{name_contains:"donna"}, {name_not:"Madonna"}]}]}){name}
```

We are really happy with this approach.

**Comment by akre54** [comment]
You could try something like https://github.com/taion/graphql-type-json. Basic gist is to create a new GraphQLScalarType and use the serialize and parse methods.

**Comment by jodinathan** [comment]
> Fwiw, at Graphcool we generate a filter input type pretty much like you describe based on the fields in a given model.
> 
> This allows arbitrary queries like this in a typed system (and auto-complete in GraphiQL):
> 
> ```
> allArtists(filter:{OR:[{name:"Madonna"}, {AND:[{name_contains:"donna"}, {name_not:"Madonna"}]}]}){name}
> ```
> 
> We are really happy with this approach.

but this can make your type list increase dramatically, doesn't it?
dunno if that is a problem thought

**Comment by jodinathan** [comment]
> Fwiw, at Graphcool we generate a filter input type pretty much like you describe based on the fields in a given model.
> 
> This allows arbitrary queries like this in a typed system (and auto-complete in GraphiQL):
> 
> ```
> allArtists(filter:{OR:[{name:"Madonna"}, {AND:[{name_contains:"donna"}, {name_not:"Madonna"}]}]}){name}
> ```
> 
> We are really happy with this approach.

Also, from your example, you can't have two blocks of logic of same type, ie:

```
AND (
    foo = 1,
    OR (
      bar = 2,
      // below we can have either a block where zas is 3 and yus is 4 or the opposite
      // thus having two times the AND block
      AND (
        zas = 3,
        yus = 4
      ),
      AND (
        zas = 4,
        yus = 3
      )
    )
  )
```

**Comment by benjie** [comment]
> Also, from your example, you can't have two blocks of logic of same type, ie ...

```graphql
{allArtists(filter: {
  AND: [
    {foo: 1},
    {OR: [
      {bar: 3},
      {
        AND: [
          {yas: 3},
          {yus: 4}
        ]
      },
      {
        AND: [
          {yas: 4},
          {yus: 3}
        ]
      }
    ]}
  ]
})}
```

(this could be expressed much simpler, but I tried to reflect your structure).
