### ISSUE TITLE
Incoherent description for default value in an argument

### ISSUE THREAD

**Issue by anmonteiro** [graphql/graphql-spec#507]
The caption for [example nr. 174](http://facebook.github.io/graphql/June2018/#example-0877c) reads:

> In the example above, an optional variable is allowed to be used in an non‐null argument which provides a default value.

but the code snippet doesn't show an example with a default value:

```graphql
query booleanArgQueryWithDefault($booleanArg: Boolean) {
  arguments {
    optionalNonNullBooleanArgField(optionalBooleanArg: $booleanArg)
  }
}
```

**Comment by IvanGoncharov** [comment]
@anmonteiro It's correct, by `non‐null argument which provides a default value` it means `optionalBooleanArg `:
http://facebook.github.io/graphql/June2018/#example-1891c
> optionalNonNullBooleanArgField(optionalBooleanArg: Boolean! = false): Boolean!

But I agree that it could be confusing do you know how to make it more clear?
If so can you please open a PR.

**Comment by anmonteiro** [comment]
Ah you're right; it's easily missed if one is skimming the spec instead of reading it from top to bottom (guilty!). Perhaps a reference to the schema above would be useful, but then it's arguable whether that should be in all examples or not :/
