### ISSUE TITLE
Allow single digits as Enums values

### ISSUE THREAD

**Issue by andrei-anisimov** [graphql/graphql-spec#508]
Currently the regex expression validating enum values is `^[a-zA-Z][_a-zA-Z0-9]*$`, which prevents starting values with a digit or having single digit values. Such values are commonly needed in applications. For example: number of people in your company, schedule intervals, evaluation scores, etc. 

Is there a way to change the regex to `^[a-zA-Z0-9][_a-zA-Z0-9]*$`?

**Comment by IvanGoncharov** [comment]
@andrei-anisimov It was discussed previously biggest problem here is code generation since digits are not valid identifiers in the absolute majority of programming languages.
Can you please describe your use case?
Do you need it to autogenerate UI or something similar?

**Comment by andrei-anisimov** [comment]
@IvanGoncharov got you, I wasn’t aware of that (I did a quick search in open issues). Correct, our use case is generating the UI, but also providing a GraphQL api for our users to build custom front-end against. So far we’ve solved this limitation by prepending “item_” to each enum option, but our front-end devs have been complaining about this.

**Comment by leebyron** [comment]
The ability to generate enum identifiers is definitely the reason for this limitation - changing the regex would break that functionality.

If it absolutely must be a number, perhaps using `Int` instead of `Enum` would suffice? You should probably describe in your field description that there's an expected max, though note that Enums may expand over time as well, so client code should still protect against future unknown int values.

**Comment by IvanGoncharov** [comment]
> So our clients have to download 2 schemas: GraphQL and our own custom. However, I’m not convinced that this will benefit the standard long term, because this can over time lead to people lobbying different metadata to be included in spec, bloating it. In other words, this could work only if metadata is fully opaque.

@andrei-anisimov Full agree. I don't think we should convert GraphQL into data validation standard but it would great to have the ability to serve opaque data attached to types through introspection.

**Comment by IvanGoncharov** [comment]
> The ability to generate enum identifiers is definitely the reason for this limitation - changing the regex would break that functionality.

@leebyron That said, can you please clarify how you would see the end result of this RFC.
Relax regex to allow number strings or the ability to attach opaque data to GraphQL types?

**Comment by leebyron** [comment]
I left it open to allow for discussion towards other solutions, but I don’t know what the right solution is (I’m not sure I fully understand the problem)

I think allowing number strings will break too many things - I’d say that’s pretty firmly out.

**Comment by leebyron** [comment]
Closing this issue since the original restriction and rationale remains. There doesn't seem to be a proposal here.
