### ISSUE TITLE
Ampersand ('&') is not part of the Punctuator production

### ISSUE THREAD

**Issue by CornedBee** [graphql/graphql-spec#573]
The Punctuator lexical token does not contain the ampersand '&'. However, this symbol is used in the ImplementsInterfaces production later on.

This appears to be an oversight. '&' should be added to the Punctuator production.

**Comment by IvanGoncharov** [comment]
@CornedBee You're absolutely right 👍 
Do you want to work on PR?

**Comment by CornedBee** [comment]
I created a PR.

**Comment by IvanGoncharov** [comment]
@CornedBee Thanks 👍 
I'm closing this issue since change is tracked in #574
