### ISSUE TITLE
GraphQL server fault tolerance and scalability?

### ISSUE THREAD

**Issue by iamyohann** [graphql/graphql-spec#578]
I have two questions:

1. Whats the recommended approach to handle failures of the GraphQL server. Most resources online describe a single GraphQL server and multiple data sources. The single GraphQL server is a single point of failure. Apart from an active / passive (shadow master) approach, are there any other approaches?

2. With the above question in mind, the single GraphQL server is also a bottleneck in terms of throughput. Are GraphQL servers stateless or stateful (with subscriptions enabled)? How do I horizontally scale GraphQL across multiple nodes? How does it keep a track of subscriptions? Can I put GraphQL behind a load balancer?

**Comment by IvanGoncharov** [comment]
> Whats the recommended approach to handle failures of the GraphQL server. Most resources online describe a single GraphQL server and multiple data sources. The single GraphQL server is a single point of failure.

There was some discussion about it here: https://github.com/graphql/graphql-spec/issues/569

But please note this repo is intended for exclusively to tracking changes/proposals to GraphQL specification.

In general there no recommended approach to how you should run your GraphQL server it's up to the community and vendors to figure out the best architectural patterns for different domains and platforms.

So I would recommend you ask the broader GraphQL community:
> Have a question? Find community resources at graphql.org/community
