### ISSUE TITLE
Support for Binary or Unary and richer data types

### ISSUE THREAD

**Issue by abdul-takt** [graphql/graphql-spec#582]
Will there be support for Binary and Unary types? Example would be Maybe, Either, or Pair type, commonly found in Haskell.

http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Either.html
http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Maybe.html
https://en.cppreference.com/w/cpp/utility/pair

In addition to supporting the above types, supporting more complex type definitions for example:

```purescript
field1 :: Pair Integer String
field2 :: Maybe Int
field3 :: Either String Integer
```

**Comment by leebyron** [comment]
The equivalent of the `Either` or `Pair` type in GraphQL is `Union`, and the equivalent of `Maybe` is nullable.

If you would like to propose kinds of types different from these, it would be worthwhile to suggest an RFC. See the CONTRIBUTING.md file in this repo for some guidance on that process.
