### ISSUE TITLE
Operations which return scalars / no selection set

### ISSUE THREAD

**Issue by IronGremlin** [graphql/graphql-spec#591]
The spec seems to indicate that all operations require a selection set.

However, when an operation returns a scalar, including a selection set is not treated as valid, because a scalar has no fields.

Documentation and reference implementations seem to indicate that scalars are considered a valid output type for an operation, and that in this case, no selection set should be provided.

Is this an issue with the spec, or an issue with the implementation that snuck into the docs?

**Comment by langpavel** [comment]
Indeed, query, mutation and subscription on schema are typically not scalars so there is always selection set on QueryType or MutationType...

**Comment by benjie** [comment]
[Section 3.2.1 of the GraphQL spec](https://graphql.github.io/graphql-spec/draft/#sec-Root-Operation-Types) states (emphasis mine):

> The query root operation type must be provided and **must be an Object type**.

> The mutation root operation type is optional; if it is not provided, the service does not support mutations. If it is provided, it **must be an Object type**.

> Similarly, the subscription root operation type is also optional; if it is not provided, the service does not support subscriptions. If it is provided, it **must be an Object type**.

Therefore the operation types themselves (Query, Mutation, Subscription) are always (if they exist) object types. Thus any GraphQL operation must have at least one selection set.

Have I understood your question correctly, @IronGremlin?

**Comment by IvanGoncharov** [comment]
@benjie Thanks for the excellent answer 👍 

@IronGremlin I suspect that you were confused by `operation` term, in GraphQL it just means the whole query, mutation or subscription. So to make this simple `data` field in GraphQL response is always an object or null.
If we didn't answer your question, please comment here and I will reopen this issue.
