### ISSUE TITLE
Question about directives for InputValue

### ISSUE THREAD

**Issue by sungam3r** [graphql/graphql-spec#611]
InputValue Type [section](https://github.com/graphql/graphql-spec/blob/master/spec/Section%204%20--%20Introspection.md#the-__inputvalue-type) in spec states:

> The __InputValue type represents field and directive arguments as well as the inputFields of an input object.

I don’t understand what directives have to do with InputValue.

**Comment by benjie** [comment]
Hi @sungam3r; directives (such as `@include(if: Boolean)`) take arguments in the same way that fields do, these are input values.

**Comment by sungam3r** [comment]
Now understood. I somehow incorrectly read the specification first. Thanks.
