### ISSUE TITLE
5.5.2.2 example error 

### ISSUE THREAD

**Issue by sungam3r** [graphql/graphql-spec#613]
[This](https://github.com/graphql/graphql-spec/blob/master/spec/Section%205%20--%20Validation.md#fragment-spreads-must-not-form-cycles) states that
```
fragment ownerFragment on Dog {
  name
  pets {
    ...dogFragment
  }
}
```

1. Fragment target should not be `Dog` (`Human`?).
2. There is no field `pets` in the schema listed in the beginning of Validation page of this spec.

**Comment by IvanGoncharov** [comment]
@sungam3r Nice catch, both points are absolutely correct 👍 
Do you want to work on PR(`on Dog` => `on Human` and add `pets`)?
