### ISSUE TITLE
Input Union RFC Discussion

### ISSUE THREAD

**Issue by binaryseed** [graphql/graphql-spec#617]
This Issue is a centralized location for discussing the collaborative RFC document which outlines the various **Input Union** solutions that have been proposed by the community:
* https://github.com/graphql/graphql-spec/blob/master/rfcs/InputUnion.md

**Comment by markokr** [comment]
How about combination:

Rule 1. Either each type has unique set of required fields (not including __typename)
Rule 2. Or __typename is required field across all types.

This makes decision making deterministic, and problems can be reported during schema compilaiton time.

Schema designers can choose what they prefer.

**Comment by binaryseed** [comment]
I'm going to close this Issue in favor of PRs into the RFC document itself.
