### ISSUE TITLE
Introspection get the whole data structure at once without describing it in the query

### ISSUE THREAD

**Issue by daspete** [graphql/graphql-spec#656]
It would be very useful, if we can get an introspection endpoint, where we can get a response of the full nested tree object for all used subtypes of a type

for example, if we have a type called "Page" and inside, we have the id and status, which are just scalars.... but for example we have a title field, which can be multilanguage

so we create a type called "LocaleContent" which have subfields like locale and content... all good, just one stage deep...

but, what if we got a type called "Seo" and inside, we have a field called description, which is also multilanguage.... and so on...

it would be great to have at least a single point, we can recursively fetch the complete data structure of a type without knowing, what is inside the type...

if we can't have that, we all are ending up writing an introspection __type query, which is 100th of lines long.... which is a mess

**Comment by rivantsov** [comment]
like 
page { * }
?

syntax suggestions pls
I like the idea, but expect it rightly objected by many...

**Comment by sungam3r** [comment]
> it would be great to have at least a single point, we can recursively fetch the complete data structure of a type without knowing, what is inside the type...

This is contrary to the core GraphQL ideas. This issue relates to the locked some time ago #127 .

**Comment by daspete** [comment]
> 
> 
> like
> page { * }
> ?
> 
> syntax suggestions pls
> I like the idea, but expect it rightly objected by many...

Hello there,

ou, this was a loong time ago :) we have overcome this issue, by just calling a introspection query:

```
query {
    __schema {
        types {
            name
            fields {
                name
            }

            inputFields {
                name
                type {
                    name
                }

                defaultValue
            }

            possibleTypes {
                name
                kind
            }
        }
    }
}
```

and in the admin interface, we just iterate recursively through the needed type fields... it's a but hacky... but it works good so far...
