### ISSUE TITLE
How to handle duplicate Input Object Value field names

### ISSUE THREAD

**Issue by fluidsonic** [graphql/graphql-spec#664]
The specification for [Input Object Values](https://graphql.github.io/graphql-spec/draft/#sec-Input-Object-Values) does not state how duplicate field names in object values are handled, for example:

```javascript
{ a: 1, a: 2, b: 3 }
```

The JS library simply [uses](https://github.com/graphql/graphql-js/blob/390000eb5425cf24129def35d5e926baf206f93f/src/utilities/valueFromAST.js#L116) the "last" field value for each name.

Duplicate field names in an object value should probably throw an error.

**Comment by IvanGoncharov** [comment]
> Duplicate field names in an object value should probably throw an error.

@fluidsonic It's already in the spec.
For value literals: https://graphql.github.io/graphql-spec/draft/#sec-Input-Object-Field-Uniqueness
For query variables we expect the input to be:
https://graphql.github.io/graphql-spec/draft/#sel-GAHhBTDABmCB0E6-Y
> unordered map supplied by a variable, otherwise a query error must be thrown. 

> The JS library simply uses the "last" field value for each name.

It's done by JS itself:
```js
const a = { a: 1, a: 2 };
console.log(a); // { a: 2 }
```

**Comment by fluidsonic** [comment]
Thank you so much for pointing me there. I've scanned the document several times for uniqueness and have no idea how I've missed that passage.
