### ISSUE TITLE
graphql spec website is broken

### ISSUE THREAD

**Issue by glasser** [graphql/graphql-spec#670]
The URL https://graphql.github.io/graphql-spec/ no longer works.

It redirects to http://graphql.github.io/ which appears identical to https://graphql.org/

There is a "Spec" link at the top that just continues the same cycle.

**Comment by michaelstaib** [comment]
I can confirm this.

**Comment by sungam3r** [comment]
Wow, I recently did PR with these links: APIs-guru/graphql-over-http#58

**Comment by benjie** [comment]
This seems to work now - redirects to https://spec.graphql.org/

I think this can be closed.

**Comment by glasser** [comment]
Seems mostly right. Annoyingly my browser seems to have ultra cached a redirect from http://spec.graphql.org/ (not https) to http://graphql.github.io/

And https://graphql.org/ 's Spec link currently is to https://graphql.github.io/graphql-spec/ which currently redirects to http://spec.graphql.org/

I might not be the only one with this ultra cached redirect. Perhaps it would be nice to link directly to https://spec.graphql.org/ (with https) from the main page?  That doesn't seem to have a cached 301 for me (and it's more https-y and less redirect-y for everyone).
