### ISSUE TITLE
Update 3.7 Interfaces grammar?

### ISSUE THREAD

**Issue by sungam3r** [graphql/graphql-spec#672]
It seems to me that #373 forgot to update 3.7 Interfaces grammar. There should be `ImplementsInterfaces` token like one in _3.6 Objects_.

**Comment by IvanGoncharov** [comment]
@sungam3r Good catch 👍 
Can you open a PR for that?

**Comment by sungam3r** [comment]
@IvanGoncharov done

**Comment by IvanGoncharov** [comment]
@sungam3r Thanks 👍 

Tracked in #680

**Comment by leebyron** [comment]
🤦‍♂  Thank you for catching and fixing this!
