### ISSUE TITLE
[RFC] Composable directives

### ISSUE THREAD

**Issue by leoloso** [graphql/graphql-spec#683]
I have just submitted an RFC concerning composable fields (#682). Composable directives are similar: they would allow directives to modify the behaviour of, or prepare the context for, other directives.

Currently, several directives can modify a field, executed in a specific order:

```graphql
query {
  field @directive1(arg1: value1) @directive2
}
```

However, we can't establish to execute a directive within another directive, because the syntax `@` doesn't support it. Then, this RFC must also involve introducing a new way to define directives, such as using `<...>`:

```graphql
query {
  field<directive1(arg1: value1)<directive2>>
}
```

In this case, the field is modified by a combination of `directive1` and `directive2`, where `directive1` wraps `directive2` like this: it first prepares the context for `directive2`, then executes it, and finally does some clean up work.

How could this be useful? For instance, it can enable to use existing directives to modify the elements of an array, like in this example:

We have a directive `translate`, which translates a field of type string ([run example in GraphiQL](https://newapi.getpop.org/graphiql/?query=query%20%7B%0A%20%20posts%3Aposts(limit%3A10)%20%7B%0A%20%20%20%20title%0A%20%20%20%20translatedTitle%3Atitle%40translate(from%3A%22en%22%2Cto%3A%22es%22)%0A%20%20%7D%0A%7D)):

```graphql
query {
  posts:posts(limit:10) {
    title
    translatedTitle:title@translate(from:"en",to:"es")
  }
}
```

Now, we have a field that resolves to an array of strings, like property `tagNames`:

```graphql
query {
  posts:posts(limit:10) {
    tagNames
  }
}
```

We can't directly use directive `translate`, since it expects a string as input, not an array of strings. We could have this directive also be able to process an array of strings; however, this would go against type safety, and it would not be a long-term solution, because it would not work for yet other inputs (eg: an array of array of strings, a map, etc).

The solution, then, is to have a directive `forEach` that can iterate through all the elements of the array, and execute the directive `translate` on each of them. Because directives are composable, it can handle any input (eg: an array of array of strings, or a map) already on the query, without any custom server-side code.

**Demonstration of the solution**

This solution has been implemented [for this GraphQL server](https://github.com/getpop/graphql). Because the GraphQL syntax doesn't support this feature, I have used [an alternative syntax](https://github.com/getpop/field-query). 

Example of a query with composable directives ([view response](https://newapi.getpop.org/api/graphql/?query=posts(limit:10).tagNames|tagNames@translatedTagNames%3CforEach%3Ctranslate(from:%22en%22,%20to:%22es%22)%3E%3E)):

```graphql
/?
query=
  posts(limit:10).
    tagNames|
    tagNames@translatedTagNames<forEach<translate(from:"en", to:"es")>>
```

**Comment by michaelstaib** [comment]
In my opinion you can already do what you want with the old syntax.

To me it appears that you want some kind of a pipelining here.

since in GraphQL the directive order is significant and we have repeatable directives you can actually define pipelines by just adding the directives in the correct order.

```graphql
query {
  posts(limit:10) @http_get(url: "...") @json(path: "$.foo.bar") @translate(from:"en", to:"es") {
    text
  }
}
```

Also the syntax that you are using is looking more like a generic approach.

For me the syntax looks to complex and the functionality can easily achieved otherwise.

**Comment by leoloso** [comment]
@michaelstaib I agree that the new `<>` syntax is not the best, but it enables to wrap elements within each other. That's why I chose it.... but if anybody suggests something better, it's welcome.

Concerning piping, I think you could achieve the same `forEach` behaviour I described, but in 3 steps instead of 2:

1. Spread the array into a series of strings
2. Translate each of them
3. Join all the translated strings into an array again

Then it would be something like this:

```graphql
query {
  posts {
    title @spread @translate(from:"en",to:"es") @join
  }
}
```

This solution looks a bit hacky to me. Certainly not as simple or elegant as through composable directives.

Also, I don't think that piping can always make it. For instance, if we want to advance a pointer to a specific position in a multi-dimensional array, and only apply the operation on that item... through composable directives, though, it could be very easy to do

**Comment by sungam3r** [comment]
Completely agree with @michaelstaib

**Comment by leoloso** [comment]
Since it's been argued that this is not a good idea, then I'm closing this issue.
