### ISSUE TITLE
Add GraphQL UDL For Notepad++

### ISSUE THREAD

**Issue by atlowell-smpl** [graphql/graphql-spec#689]
As the title suggests, this is a feature request for a user-defined language file for GraphQL syntax highlighting for Notepad++.  An auto-complete file would also be useful.

**Comment by IvanGoncharov** [comment]
@atlowell-smpl Hi Austin,
Sadly we don't have resources to support all possible editors/IDEs but we provide an implementation of Language Server Protocol for GraphQL: https://github.com/graphql/graphiql
Also, GraphQL Specification have a full grammar that you can port into Notepad++ format: https://spec.graphql.org/June2018/#sec-Appendix-Grammar-Summary
