### ISSUE TITLE
Allow importing of constants from .js file into .graphql file.

### ISSUE THREAD

**Issue by U-4-E-A** [graphql/graphql-spec#695]
I am building a schema that includes an enum. The enum values are based on constants from other files, but they are in the .js format.

For instance, I would like to be able to do the following...

models/blah.js: -

```
export const BLAH1 = "blah1"
export const BLAH2 = "blah2"
```

enum.graphql: -

```
# import BLAH1, BLAH2 from "./models/blah"

enum StatusEnum { ${BLAH1} ${BLAH2} }
```

As far as I can see, there is no way of doing this. I could graphql-compose but I would like to keep things clean and simple with just .graphql files. This functionality would be hugely appreciated by me.

**Comment by sungam3r** [comment]
How does this relate to the GraphQL **language** specification?

**Comment by IvanGoncharov** [comment]
@U-4-E-A GraphQL is a language-independent specification so we can't import stuff from JS or any other programming language.
What you can do is to generate enums programmatically (using `graphql-compose`, `graphql-js`, etc.) and keep all other types in `.graphql` files.
