### ISSUE TITLE
graphql schema filed names having @symbol gives syntax error

### ISSUE THREAD

**Issue by sureshdarisa** [graphql/graphql-spec#734]
I am calling REST API endpoint by sending request and the request json fields contain names that start with @ symbol, but Graphql input schema not compiled and throws syntax error. Is there any solution to fix this issue.

input Tax {
    taxCategory: String
    taxRate: Float
    taxAmount: TaxAmount
    @baseType: String
    @type: String
}

**Comment by IvanGoncharov** [comment]
GraphQL supports only letters, digits and underscore in field names.
You can try to replace `@` with underscore `_`.
Also please note it's repo for proposal to graphql specification please use community resources for solving issues like that
https://graphql.org/community/
