### ISSUE TITLE
Question about list of lists

### ISSUE THREAD

**Issue by sungam3r** [graphql/graphql-spec#749]
Reading the specification, I did not see anywhere an explicit description of whether `LIST` can wrap `LIST` or `NON_NULL` can wrap `NON_NULL` (or even more than 2 times). The latter seems pointless to me but the first is quite normal - `[[1,2,3],[4],[5,6]]`. Is it possible?

**Comment by akshatj355** [comment]
I think , it is possible.

**Comment by sungam3r** [comment]
@leebyron @benjie @spawnia ?

**Comment by benjie** [comment]
I don't see anything in the spec that forbids this, and it works in the reference implementation:

```js
const {
  graphqlSync,
  GraphQLSchema,
  GraphQLObjectType,
  GraphQLList,
  GraphQLString,
  printSchema,
} = require("graphql");

const Query = new GraphQLObjectType({
  name: "Query",
  fields: {
    listOfLists: {
      type: new GraphQLList(new GraphQLList(GraphQLString)),
      resolve() {
        return [["a", "b", "c"], ["d"], [], ["e", "f", "g", "h"]];
      },
    },
  },
});

const schema = new GraphQLSchema({
  query: Query,
});

console.log(printSchema(schema));

const { data, errors } = graphqlSync(
  schema,
  /* GraphQL */ `
    {
      listOfLists
    }
  `
);

console.dir({ data, errors }, { depth: 8 });
```

```
type Query {
  listOfLists: [[String]]
}

{
  data: [Object: null prototype] {
    listOfLists: [ [ 'a', 'b', 'c' ], [ 'd' ], [], [ 'e', 'f', 'g', 'h' ] ]
  },
  errors: undefined
}
```

The main issue you'll get is introspection; the normal introspection query [only queries 6 layers of wrappers](https://github.com/graphql/graphql-js/blob/65889192ae28969729385e24e76bbcc04d61e9c6/src/utilities/getIntrospectionQuery.js#L106-L137) so more GraphQLNonNull/GraphQLLists than that will cause issues with tooling probably.

**Comment by spawnia** [comment]
> A Non‐Null type must not wrap another Non‐Null type.

http://spec.graphql.org/draft/#sec-Type-System.Non-Null.Type-Validation

As @benjie said, there is nothing in the spec that forbids nesting lists. There are even examples of it in the input coercion section http://spec.graphql.org/draft/#sec-Type-System.List.Input-Coercion

I think adding an extra example won't hurt so I created https://github.com/graphql/graphql-spec/pull/755

**Comment by sungam3r** [comment]
@benjie @spawnia Thank you for examples and pointing the specs parts.

**Comment by benjie** [comment]
@sungam3r If this is solved please close the issue :+1:
