### ISSUE TITLE
GraphQL query: skip value field if null

### ISSUE THREAD

**Issue by Kunjahamed-P** [graphql/graphql-spec#766]
Is there any option in graphql to skip field is null, first I apologize if this makes no sense. 
```
query Hero {
  hero {
    name
    friends {
      name
    }
  }
}
```
in here I want to hide/skip `friends` object is null
It would reduce an extra line of logic from a front end developer point and hide unwanted empty data. (In our implementation we are added authorization status in all object, we want only show object have any authorization message exist)
I already read in [@include(unless null)](https://github.com/graphql/graphql-spec/issues/275)

**Comment by JohannSig** [comment]
Want this

**Comment by leebyron** [comment]
Maybe I'm misunderstanding your request, but I think you're describing the existing behavior? In this example if the `friends` field produces a `null` value, then the sub-selections will be skipped. You'll see `"friends": null` in the result, and not something like `"friends": { "name": null }` since that implies something different.

**Comment by leebyron** [comment]
If you're talking about fully omitting entries from the response if their value is `null`, that's been proposed before and rejected. It's important for a client to know that a server interpreted their query correctly and returned the correct data. `{"friends": null}` gives you important information that this field has no value, where as `{}` does not tell you anything except that a field value was not included in the response.

This is important to ensure that responses can be interpreted accurately even when the original query is not available.

Here's another example for an alternate way to think about this: If a `Hero` type also has a field `sidekick` which you did not add to your query, and you see the response `{ "friends": [...] }` - this should not imply that this Hero has no sidekick, it should only imply that sidekick was not queried.

**Comment by fmaerkl-sw** [comment]
Late, but perhaps still relevant:

> This is important to ensure that responses can be interpreted accurately even when the original query is not available.

How is is it even possible at all with the current specification to interpret a response without the query? Let's say I perform the following query on the same schema used in your sidekick example:
```graphql
query Hero {
  hero {
    friends: sidekick
  }
}
```

Now I get e.g. `{ "friends": ... }`, a similar reponse to the one in your example, just maybe with different types and data under "friends". You claim that such a response implies that
> sidekick was not queried

But in fact sidekick *was* queried.

---

On the other hand, assuming we are always interpreting our responses in combination with the query, we could define skipped fields in the response that were included in the query as implicitly null. This is particularly useful when having objects with a large number of fields, but only a few of them being set in practice, e.g.:
```graphql
type QuizQuestionAnswer {
  fieldA: Boolean
  fieldB: String
  fieldC: Int
  (...)
}
```
In practice, this may be somewhat of a code smell, but there can be cases where this is exactly what is needed.

Now querying a long list of such objects would result in a lot of redundant `{"fieldA": null, "fieldB": null, "fieldC": null, (...)}` with current graphql. Generic compression like gzip can be very effective in reducing the amount of data on the network, but it will still be a lot of unnecessary data to be generated, compressed, decompressed and parsed in the end.
