### ISSUE TITLE
Spec should be more explicit about whether NaN and Inf are valid Floats

### ISSUE THREAD

**Issue by glasser** [graphql/graphql-spec#778]
[The spec documents the Float type](https://spec.graphql.org/draft/#sec-Float) as representing "signed double‐precision fractional values as specified by IEEE 754".

In addition to "normal" finite numbers, [IEEE 754 includes NaN and positive and negative infinity](https://en.wikipedia.org/wiki/IEEE_754).

A plain reading of section 3.5.2 would imply that the GraphQL Float type includes all IEEE 754 values, not just the finite ones.

However, I don't believe this is the intent. First, you cannot express these values as literals, which is [very clear in the definition of FloatValue](https://spec.graphql.org/draft/#sec-Float-Value). Secondly, the reference implementation GraphQL-JS [explicitly rejects non-finite values](https://github.com/graphql/graphql-js/blob/16009cbcb0109da03f2157a868817b886801095a/src/type/scalars.js#L108-L112) (introduced by @IvanGoncharov in https://github.com/graphql/graphql-js/pull/1365 and @leebyron in https://github.com/graphql/graphql-js/pull/1382).

The only allusion to NaN in the spec is in [the value completion section](https://spec.graphql.org/draft/#sec-Value-Completion) which it suggests that mapping NaN to null may be appropriate (I don't believe graphql-js does this, though).

I think the right fix is to change the Float section to be clear that only IEEE 754 finite values are part of the Float type (and maybe to remove the note about NaN mapping to null).  Happy to send a PR if folks agree.

**Comment by juriad** [comment]
I encountered a similar problem in graphql-java regarding the range of Float and infinities. I also couldn't find a definite answer in the spec. https://github.com/graphql-java/graphql-java/issues/1998

**Comment by benjie** [comment]
Does "fractional values" not exclude NaN and Infinity? Either way, we could definitely clarify that we only support finite values; I encourage you to send a PR and add it to the next GraphQL Working Group call.

**Comment by glasser** [comment]
@benjie Thanks, I filed #780. It seems like this is just "clearing up ambiguity" and doesn't need a full RFC process — do I need to add it to the working group somehow?

**Comment by benjie** [comment]
Yeah, please add it as a 5m topic to https://github.com/graphql/graphql-wg/blob/master/agendas/2020-10-01.md. I think it's fairly non-controversial, so as long as there's not too much bike-shedding it should be a quick approval.
