### ISSUE TITLE
Possible support for non-empty fields: String!!

### ISSUE THREAD

**Issue by jigarius** [graphql/graphql-spec#782]
Say, my application wants to have a required `name` field.
  * Currently, it is possible to have non-nullable field, e.g. `String!`
  * However, the client can get away with `''` as a value.
  * I was wondering if it makes sense to have something like `non-empty` fields, maybe with a syntax like `String!!`?

If `name` is of type `String!!`, then it cannot take values like:
  * `null`
  * `''`
  * `   `

Most languages have a concept of `empty` alongside `nil/null`. So, this should help with validating empty values.

**Comment by mike-marcacci** [comment]
I would probably lump this into "format validation" much like a "prime number" or "email address". To accomplish this in the current state, try defining a custom scalar like `NonEmptyString`. Your implementation can validate the values when parsing and serializing.

**Comment by sungam3r** [comment]
@jigarius what about `Int!!`, `Float!!` or `MyCustomType!!`? I agree with @mike-marcacci

**Comment by jigarius** [comment]
Well, `Int!!` and `Float!!` would be non-zero numbers. However, for custom types, the type will have to define what's empty and what's not. But it sounds okay to have a custom implementation for such logic.

I made the suggestion because languages like PHP and Ruby seem to already have the concept of `empty`. e.g.

  * `[]`, an array with zero elems, is empty.
  * `0` is an empty float or integer.
  * `''` is an empty string and so is `'   ``.
