### ISSUE TITLE
List of type definitions in type system definition

### ISSUE THREAD

**Issue by vwkd** [graphql/graphql-spec#788]
I'm reading the definition of a type system in the [spec](http://spec.graphql.org/draft/#TypeSystemDefinition)

```plaintext
TypeSystemDefinition:
   SchemaDefinition
   TypeDefinition
   DirectiveDefinition
```

which allows only a single type definition. Shouldn't this allow for a list of type definitions instead? In other words, shouldn't it be

```plaintext
TypeSystemDefinition:
   SchemaDefinition
   TypeDefinition+
   DirectiveDefinition
```

where the `+` denotes the subscript "list".

Because currently, the single type definition wouldn't allow me to define a type system like

```graphql
schema {
  query: MyQuery
  mutation: MyMutation
}

type MyQuery {
  myField: String
}

# One TypeDefinition too much!
type MyMutation {
  setMyField(to: String): String
}
```

Actually, since `Document: Definition+`, the above is still a valid document if one reads the second `TypeDefinition` as being from another `TypeSystemDefinition` in another `Definition`. But this isn't intended, or is it?

EDIT: I haven't yet read the definition for a directive, but I guess using the same argument `DirectiveDefinition` should be `DirectiveDefinition+`?

**Comment by benjie** [comment]
> Actually, since Document: Definition+, the above is still a valid document if one reads the second TypeDefinition as being from another TypeSystemDefinition in another Definition. But this isn't intended, or is it?

This is intended. A `TypeSystemDefinition` is a singular definition which may be one of `SchemaDefinition`, `TypeDefinition` or `DirectiveDefinition`. A document is composed of a list of singular definitions; as can be seen by `Document: Definition+` as you note.

**Comment by vwkd** [comment]
@benjie Thanks for clarifying that this is actually as intended. It does seem weird to me though that each `TypeDefinition` needs to have its own `TypeSystemDefinition` because, purely logically speaking, the schema defines a single type system not multiple. But since the resulting document stays the same this terminology doesn't matter much I guess. I'm happy to close this and will close the PR as well.

**Comment by benjie** [comment]
>  It does seem weird to me though that each TypeDefinition needs to have its own TypeSystemDefinition

I think you might be misreading it. Effectively `TypeSystemDefinition` is an abstract union which would be satisfied by one of `SchemaDefinition`, `TypeDefinition` or `DirectiveDefinition`; these are definitions that are valid within the type system: they are TypeSystemDefinitions. A GraphQL document can contain both type system definitions and executable definitions; although a document containing both would likely not be used to execute queries nor to define a schema it could be useful for documentation or other tooling purposes.

**Comment by vwkd** [comment]
Makes sense that for documentation / tooling purposes a single document should be valid, even if it contains multiple schemata or TypeSystemExtensions without TypeSystemDefinitions. I think I was looking at it from an "execution point-of-view" where a document is only used for defining the schema and/or making a request.

Thanks, I'l close this.
