### ISSUE TITLE
Is there a way to get the Dependents of the Dependency graph?

### ISSUE THREAD

**Issue by peterzsj6** [graphql/graphql-spec#792]
!!! IMPORTANT !!!

Before creating your issue:

* Have a question? Find community resources at https://graphql.org/community/

* Find an editing mistake? Create a Pull Request with the edited fix! The Github UI allows you to edit files directly, find the source files at: https://github.com/graphql/graphql-spec/tree/master/spec

* Improvements to documentation? Head over to https://github.com/graphql/graphql.github.io

* Feature request? First read https://github.com/graphql/graphql-spec/blob/master/CONTRIBUTING.md and prefer creating a Pull Request!

****

As mentioned above, I am trying to get the Dependents of the repo to create a network graph. I have yet to find a way to get the dependents instead of the dependencies of the repo.  Since both dependents and dependencies are in the dependency graph of the repo's insight, is there a way for me to get the dependents using graphql?

**Comment by benjie** [comment]
Hi @peterzsj6 I think your question might relate specifically to GitHub's GraphQL API which is documented here:

https://docs.github.com/en/free-pro-team@latest/graphql

(At the bottom of the page you'll find links you can follow to request help.)

If that's the case, we can't help you here as this is the repository for the GraphQL Specification which details how all GraphQL APIs should work but doesn't have specifics on GitHub's API. If it's not the case, please could you expand your question with some more context?

**Comment by peterzsj6** [comment]
> Hi @peterzsj6 I think your question might relate specifically to GitHub's GraphQL API which is documented here:
> 
> https://docs.github.com/en/free-pro-team@latest/graphql
> 
> (At the bottom of the page you'll find links you can follow to request help.)
> 
> If that's the case, we can't help you here as this is the repository for the GraphQL Specification which details how all GraphQL APIs should work but doesn't have specifics on GitHub's API. If it's not the case, please could you expand your question with some more context?

Hi benjie, I am sorry about this. It is a specific question realted to Github's API, I just could't  find the right place for this question.

**Comment by benjie** [comment]
No worries; best of luck, hopefully GitHub support can help you out 👍
