### ISSUE TITLE
ImplementsInterfaces tree-sitter grammar doesn't work when matching spec

### ISSUE THREAD

**Issue by bkegley** [graphql/graphql-spec#799]
I'm implementing a tree-sitter grammar from the GraphQL spec and not getting what I'd expect when implementing `ImplementsInterfaces`.

A valid multiple interface type definition would look like:

```graphql
type User implements Entity & Person {
  id: String
}
```

My implementation for the grammar is [here](https://github.com/bkegley/tree-sitter-graphql/blob/7096492d2029776db930283fd2213316ad01afd8/grammar.js#L129-L133). Another example doesn't quite match the spec but produces the expected output. You can see that [here](https://github.com/dralletje/tree-sitter-graphql/blob/633b20d7ab7785e84ac6b1f9c56349c9d0594d9d/grammar.js#L262-L268).

Would the spec rather be `implements &? NamedType [& NamedType]?`

**Comment by benjie** [comment]
> Would the spec rather be `implements &? NamedType [& NamedType]?`

That's what [the spec states](https://spec.graphql.org/draft/#ImplementsInterfaces) I believe (other than the `?` at the end should be `*` or whatever you use for 0-or-more).

The `&` after the `implements` keyword is optional, then it must be followed by a `NamedType` and then optionally it may be followed by any number of `& NamedType`.

I think [this line](https://github.com/bkegley/tree-sitter-graphql/blob/7096492d2029776db930283fd2213316ad01afd8/grammar.js#L132) in your code misses the fact the `&` is optional.

**Comment by bkegley** [comment]
Good catch! I think that was part of the issue.

I was also misunderstanding how recursion was working in the spec. I was working left-to-right, however, the spec is stating that `& NamedType` can be prefaced by any number of `& NamedType`s until it hits an `implements`.

Thanks!
