### ISSUE TITLE
Articulate that built-in directives not be returned from introspection results

### ISSUE THREAD

**Issue by maraisr** [graphql/graphql-spec#814]
Much like the spec currently states ["all built‐in scalars must be omitted for brevity."](https://spec.graphql.org/draft/#sel-GAHXLHABAB_DnhW).

I'd like to propose we say something similar to that, but specifically referencing this for built-in directives, namely the `@skip` and `@include` etc.. 

In the past I have been told that "we return that in the introspection so you know what the capabilities are", my answer to that is "if its in the spec, the capability SHOULD already be there, no need to tell me that". 

Granted this is an opinion of the matter, but just raising in case there is sentiment to guide what we do about umbrella built-in's, and not just built-in scalars—as this would mean tighter cohesion between different server implementations.

---

I would be open to spearheading this initiative, but will need to be hand held a tad making a PR.

**Comment by maraisr** [comment]
Keen to hear your opinion of this matter @leebyron @robrichard @n1ru4l

**Comment by sungam3r** [comment]
> **When** representing a GraphQL schema using the type system definition language

You omitted an important condition.

**Comment by maraisr** [comment]
Youre confusing me @sungam3r care to elaborate?

**Comment by maraisr** [comment]
Just feel its silly how this makes stitching multiple schemas hard, when each contain its own copy of the directive. 

What should we _assume_ we dedupe?

**Comment by maraisr** [comment]
I apologies for this.

**Comment by maraisr** [comment]
@IvanGoncharov @benjie if you care to chime in.

Worth noting, i may have said "introspection" but that's a loose term, as our server returns its sdl through an endpoint. Which is what I'm speaking too.

So yes, would love built in directives to also not be defined in the sdl

**Comment by benjie** [comment]
From [the linked PR](https://github.com/graphql/graphql-spec/pull/815#issuecomment-760790440):

> @maraisr To add some justification for not adding this change, new directives such as @defer and @stream are being added to the GraphQL Spec (i.e. they are "built in"), but support for them is optional - clients can use introspection to see whether the directive exists or not to see if the feature is supported. So I think it's worth continuing to include directives in the printed schema/introspection results.

**Comment by maraisr** [comment]
> From [the linked PR](https://github.com/graphql/graphql-spec/pull/815#issuecomment-760790440):
> 
> 
> 
> > @maraisr To add some justification for not adding this change, new directives such as `@defer` and `@stream` are being added to the GraphQL Spec (i.e. they are "built in"), but support for them is optional - clients can use introspection to see whether the directive exists or not to see if the feature is supported. So I think it's worth continuing to include directives in the printed schema/introspection results.

Can we enforce that then?
