### ISSUE TITLE
Empty descrptions

### ISSUE THREAD

**Issue by maraisr** [graphql/graphql-spec#861]
The spec fails to mention what to do in the absence of a description. It does state that descriptions should be made available when not self-descriptive, but also states that the description during introspection is a String—so should this be an empty string?

**Comment by benjie** [comment]
Since it is a `String` and not `String!` I think it’s reasonable to use `null` if no description is provided. The empty string is also a legal value.

**Comment by maraisr** [comment]
Ah perhaps an issue with java-graphql then, it doesnt like empty string descriptions. Will raise over there, thanks @benjie
