### ISSUE TITLE
Question about descriptions for TypeExtensions

### ISSUE THREAD

**Issue by sungam3r** [graphql/graphql-spec#900]
See http://spec.graphql.org/October2021/#sec-Type-Extensions : 

> Type extensions are used to represent a GraphQL type which has been extended from some original type. 

So those parts of schema are server-side.

And from http://spec.graphql.org/October2021/#sec-Descriptions:

> GraphQL schema and all other definitions (e.g. types, fields, arguments, etc.) which can be described should provide a Description unless they are considered self descriptive.

I see that extensions are used to extend schema definitions but they do not have descriptions. Is it done intentionally?

**Comment by benjie** [comment]
Type extensions don’t really “exist” once the schema is constructed so where would their descriptions go? How would you query them through GraphQL?

The only use I can think is to add or replace the description of the underlying type; but the risk there is ambiguity - what if a description is presented in both locations? Maybe it could append?

We’re currently considering adding descriptions to operations and fragments, so maybe this would make sense alongside that, but I fear it may be confusing.

What do you think?

**Comment by michaelstaib** [comment]
> The only use I can think is to add or replace the description of the underlying type; but the risk there is ambiguity - what if a description is presented in both locations? Maybe it could append?

Also if you have multiple extensions for a single type and every of those has a descriptions, which should you take. In the end, the extension will just add new fields or directives to the type. 

If you look at the type validation rule it's also clear that nothing a type extension brings is allowed to already be on the type.

**Comment by sungam3r** [comment]
OK, thanks. I thought so.
