### ISSUE TITLE
Doing atomic changes and increments

### ISSUE THREAD

**Issue by lveillard** [graphql/graphql-spec#903]
Hello all, i found this Hasura article really interesting:
https://hasura.io/blog/updating-data-using-mutations-on-hasura-graphql-87c7e22503bc/

The way they interpretate the where + increment in one mutation seems really intuitive and elagant:
![image](https://user-images.githubusercontent.com/29461076/143024973-f70c6e42-a80f-419e-ae08-3137186fbdd1.png)

Is something like this planned for the standard? 
Thanks!

**Comment by benjie** [comment]
The GraphQL spec already allows for that, so I guess mission accomplished? :tada:

**Comment by lveillard** [comment]
Oh sorry for that. I thought it was an extra layer Hasura was adding!
