### ISSUE TITLE
schema used and changed actual graphql fb.base data

### ISSUE THREAD

**Issue by fkelley047xyz** [graphql/graphql-spec#909]
!!! IMPORTANT !!!

Before creating your issue:

* Have a question? Find community resources at https://graphql.org/community/
Find an editing mistake? Create a Pull Request with the edited fix! The Github UI allows you to edit files directly, find the source files at: https://github.com/graphql/graphql-spec/tree/master/spec

* Improvements to documentation? Head over to https://github.com/graphql/graphql.github.io

* Feature request? First read https://github.com/graphql/graphql-spec/blob/master/CONTRIBUTING.md and prefer creating a Pull Request!

**Comment by benjie** [comment]
Hi @fkelley047xyz; it looks like you may have opened this issue in error. If not, please explain in more details what your issue is.
