### ISSUE TITLE
Question about naming

### ISSUE THREAD

**Issue by sungam3r** [graphql/graphql-spec#915]
Consider those parts of the spec for list nodes in GraphQL grammar:

http://spec.graphql.org/October2021/#ArgumentsDefinition
http://spec.graphql.org/October2021/#InputFieldsDefinition
http://spec.graphql.org/October2021/#FieldsDefinition
http://spec.graphql.org/October2021/#EnumValuesDefinition

_s_ before _Definition_

but for variables

http://spec.graphql.org/October2021/#VariableDefinitions

_s_ after _Definition_ . 

Was it done intentionally?

**Comment by benjie** [comment]
IMO you're right; it should be VariablesDefinition - it's a single definition, that defines all of the variables.
