### ISSUE TITLE
Question about enum names

### ISSUE THREAD

**Issue by sungam3r** [graphql/graphql-spec#919]
Hi. I see that spec defines special term for fragment name - http://spec.graphql.org/October2021/#FragmentName . For enum name I see the same but without special term - http://spec.graphql.org/October2021/#EnumValue . Why so?

**Comment by benjie** [comment]
> `FragmentName`: `Name` but not 'on'
> `EnumValue`: `Name` but not 'true' or 'false' or 'null'

@sungam3r you say "enum name" but do you mean "enum value" since that's what you linked to? In which case it does have a special term: `EnumValue`. (This is different to the type name of an enum, which is just a `Name` because there's no special syntactical constraints.)

**Comment by sungam3r** [comment]
Sorry. Now I once again carefully examined the specification and my code and it became obvious to me that no special term is needed. Thanks.

**Comment by sungam3r** [comment]
Thanks again. I found a mistake in my code. I lost one level of AST.
