### ISSUE TITLE
error occured parsing slash

### ISSUE THREAD

**Issue by onein528** [graphql/graphql-spec#934]
Hi guys. I've encountered an unhandled error that seems to be occurring while parsing a slash.

```graphql
query {
  repository (name: "FluentHub", owner: "fluenthub-community") {
    ref (qualifiedName: "main") {
      target {
        ... on Commit {
          history(first:1, path:"/") {
            totalCount
          }
        }
      }
    }
  }
}
```

output:
```graphql
{
  "errors": [
    {
      "message": "Something went wrong while executing your query. Please include `635D:67C6:6413EB:15B1836:622B23D2` when reporting this issue."
    }
  ]
}
```

FWIW:
Normally, you don't set the path to get the commit of the root, but it is used together with Octokit.NET, and I can use "\" as the root in Octokit.NET. and Octokit is GitHub but this issue breaks as NullReferenceError in Octokit.GraphQL.NET It would be nice to fix the C# code to ".", But I reported it because it was an unhandled error. Do you guys already know this within the GraphQL community?

**Comment by onein528** [comment]
This happened in GraphiQL, do I need to report to that repository? If so, can you transfer it? sorry I made a mistake.

**Comment by benjie** [comment]
Hi @onein528; this does not appear to be a bug in GraphQL's Spec or in GraphiQL, this seems to be an issue in (I'm guessing?) GitHub's GraphQL API (which we have nothing to do with). Try issuing a support request to GitHub's API support team. Good luck getting your issue resolved :+1:
