### ISSUE TITLE
Repository names with dashes cannot be requested

### ISSUE THREAD

**Issue by arhadthedev** [graphql/graphql-spec#989]
I need to get some statistics from a repository which name contains dashes (https://github.com/python/core-workflow):

```graphql
{
  repository(name: "core-workflow", owner: "python") {
    object(expression: "main") {
      ... on Commit {
        history(author: {emails: "oleg@arhadthedev.net"}) {
          totalCount
        }
      }
    }
  }
}
```

However, it cannot be requested:

```graphql
{
  "data": {
    "repository": {
      "object": null
    }
  }
}
```

Other, dashless repositories from the same organization work great:

```graphql
{
  repository(name: "cpython", owner: "python") {
    object(expression: "main") {
      ... on Commit {
        history(author: {emails: "oleg@arhadthedev.net"}) {
          totalCount
        }
      }
    }
  }
}
```

```graphql
{
  "data": {
    "repository": {
      "object": {
        "history": {
          "totalCount": 39
        }
      }
    }
  }
}
```

From gh-479 I know that no object key can contain a dash. Nonetheless, repositories with dashes in their names are totally legit so there should be a way to address them in queries.

**Comment by rivantsov** [comment]
why is this issue posted here? yes, this repo name contains dash, GitHub GraphQL API has problems with it, but what we can do about it? rename the repo?!

**Comment by arhadthedev** [comment]
> but what we can do about it? rename the repo?!

Sure, not. However, denying repositories that are valid for the rest of the whole GitHub makes GraphQL-based tools unusable for such repositories.

Here's an example from [Trending Repositories](https://github.com/trending) to demonstrate that dashed names is not a feature of some student labs needed by no-one. Dashed repo names are highlighted:

- toeverything / AFFiNE
- utmapp / UTM
- ***NVIDIAGameWorks / kaolin-wisp***
- microsoft / terminal
- jina-ai / discoart
- martinshkreli / models
- facebookresearch / ParlAI
- KalleHallden / exer_log
- ***juliocesarfort / public-pentesting-reports***
- ***EbookFoundation / free-programming-books***
- moyix / fauxpilot
- ***josejesusguzman / acordeon-az500-innoovaccion***
- adiwajshing / Baileys
- qmk / qmk_firmware
- valinet / ExplorerPatcher
- ***PKUFlyingPig / cs-self-learning***
- ***lucidrains / imagen-pytorch***
- Womsxd / AutoMihoyoBBS
- ***getify / You-Dont-Know-JS***
- coolsnowwolf / lede
- google-research / multinerf
- ***termux / termux-app***
- godotengine / godot
- ***rust-lang / rust-analyzer***
- ventoy / Ventoy

**Comment by rivantsov** [comment]
sorry, I think you have an impression that people here (around this repo) are actually in charge of Github's GraphQL API? that's not the case; you should connect to Github support team.

**Comment by arhadthedev** [comment]
> sorry, I think you have an impression that people here (around this repo) are actually in charge of Github's GraphQL API

My sincere excuses then. The README's line `This is a Working Draft of the Specification for GraphQL` gave me an impression that this repo is where GraphQL sponsors define how the world should work; something like https://github.com/w3c for the Web and https://github.com/tc39 for JavaScript aka ECMAScript.

> you should connect to Github support team.

It was unintuitive so thank you for the relevant contact.

**Comment by benjie** [comment]
@arhadthedev By the looks of your query result the repository was found because it’s non-null; the object is null - perhaps it uses an alternative main branch name such as “trunk” or “master”? I hope this helps.

**Comment by brasic** [comment]
@arhadthedev you want `object(expression: "HEAD")` to select the default branch, the repo you linked to has no ref called `main`.

**Comment by arhadthedev** [comment]
My apologises for misidentifying the problem. The repo is the only one in my list which master branch was not renamed so I didn't notice it and came googling for the error message instead.

@brasic Thank you for a name-agnostic solution.
