### ISSUE TITLE
Confused about type definitions's optional fields definitions

### ISSUE THREAD

**Issue by cutsoy** [graphql/graphql-spec#993]
Hi all,

I'm looking for some documentation on why the `FieldsDefinition` in [`ObjectTypeDefinition`](https://spec.graphql.org/October2021/#ObjectTypeDefinition) is optional. I don't think this would produce a valid definition since it violates the first type system constraint that _"An Object Type must define one or more fields."_

The same thing also applies to [`InterfaceTypeDefinition`](https://spec.graphql.org/October2021/#InterfaceTypeDefinition), [`UnionTypeDefinition`](https://spec.graphql.org/October2021/#UnionTypeDefinition), [`EnumTypeDefinition`](https://spec.graphql.org/October2021/#EnumTypeDefinition), [`InputObjectTypeDefinition`](https://spec.graphql.org/October2021/#InputObjectTypeDefinition).

I noticed the following [note in 3.3.2 Schema Extension](https://spec.graphql.org/October2021/#note-c9cd2):

> Schema extensions without additional operation type definitions must not be followed by a `{` (such as a query shorthand) to avoid parsing ambiguity. The same limitation applies to the type definitions and extensions below.

This makes sense with regards to extensions, but I don't understand why it applies to definitions as well.

Can someone point me in the right direction? What's the point of allowing type definitions without fields/members/values?

Regards,

Tim

**Comment by benjie** [comment]
> This makes sense with regards to extensions, but I don't understand why it applies to definitions as well.

It allows you to define a type at one point and add fields to it at a later point; e.g.:

```graphql
directive @someDirective on OBJECT

type Query @someDirective

type Me {
  name: String!
}

extend type Query {
  me: Me
}
```

**Comment by yaacovCR** [comment]
The validation rule applies to the type, which is "defined" by the combination of the type "definition" as well as the "extensions". The type definition can lack fields, but if the extension has fields, the combination results in a type that is valid.

**Comment by benjie** [comment]
Yes, also factor in that a GraphQL document doesn't have to pass schema validation - it might be that your schema is composed of a number of GraphQL documents, each with type definitions and/or extensions within them - it's the final GraphQL schema itself that must validate.

**Comment by cutsoy** [comment]
Ah thanks! Sorry if this was obvious but I assumed these validations applied to the AST level type definitions rather than on some IR. Makes it a little bit easier though, so thanks!

Just so I get this right, the following would be admissible, right? (although a bit of an edge case)

```graphql
type Example

interface Foo {
    foo: String!
}

interface Bar {
    bar: String!
}

extend type Example implements Foo {
    bar: String!
}

extend type Example implements Bar {
    foo: String!
}
```

_Note that the type extensions actually implement fields from another interface._

**Comment by benjie** [comment]
I believe so, yes
